name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Swift Package
    runs-on: macos-15
    permissions:
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        persist-credentials: false

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90
      with:
        xcode-version: '16.0'

    - name: Download iOS Platform
      run: |
        xcrun simctl list > /dev/null
        xcodebuild -downloadPlatform iOS

    - name: Build Swift Package
      run: xcodebuild build -scheme PortOneSdk -sdk iphoneos18.0 -destination "platform=iOS Simulator,name=iPhone 16,OS=18.0"

    - name: Build Release Mode
      run: xcodebuild build -scheme PortOneSdk -configuration Release -sdk iphoneos18.0 -destination "platform=iOS Simulator,name=iPhone 16,OS=18.0"
