name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Swift Package
    runs-on: macos-15
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0'

    - name: Build Swift Package
      run: xcodebuild build -scheme PortOneSdk -sdk iphoneos18.0 -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.6'

    - name: Build Release Mode
      run: xcodebuild build -scheme PortOneSdk -configuration Release -sdk iphoneos18.0 -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.6'
