name: Release

on:
  push:
    branches: [ "main" ]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
    - name: Setup pnpm
      uses: pnpm/action-setup@v3
    - name: Setup Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 24
    - name: Install Dependencies
      run: pnpm install
    - name: Create Release Pull Request or Publish
      id: changesets
      uses: changesets/action@v1.7.0
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Push Tags
      if: ${{ steps.changesets.outputs.hasChangesets == 'false' }}
      run: |
        export VERSION=$(jq -r '.version' package.json)
        if [ -n "$(git ls-remote --tags origin "refs/tags/$VERSION")" ]; then
          echo "Tag $VERSION already exists on remote, skipping."
        else
          git tag "$VERSION"
          git push origin "refs/tags/$VERSION"
        fi
